$.evalFile("E:/Work/GitHub/UI-DNA/DVE/bin/JSX/json3.js")
$.evalFile("E:/Work/GitHub/UI-DNA/DVE/Enzymes/test/test.jsx")
$.evalFile("E:/Work/GitHub/UI-DNA/DVE/Enzymes/Enzymes_lib.jsx")

//EnzJSX.setLayerInfo_shape_byId  ({"lineWidth":"10"}, 417)
//EnzJSX.setLayerInfo_shape_byId  ({"fillColorEnabled":false}, 390)
 // var ob = Kinase.layer.getLayerInfoObject_byActiveLayer()
 //var ob =Kinase.layer.getLayerEffectsObject(Kinase.REF_ActiveLayer, null)
  //    var ob = Kinase.layer.get_XXX_Objcet(Kinase.REF_ActiveLayer, null, "layerEffects")


 //ob=Kinase.layer.getEffectsList_universal (ob,"dropShadow")
 
 
 
 
  log(json(ob))