$.evalFile("E:/Work/GitHub/UI-DNA/DVE/bin/JSX/json3.js")
$.evalFile("E:/Work/GitHub/UI-DNA/DVE/Enzymes/test/test.jsx")
$.evalFile("E:/Work/GitHub/UI-DNA/DVE/Enzymes/Enzymes_lib.jsx")
$.evalFile("E:/Work/GitHub/UI-DNA/DVE/Proteins/Proteins_lib.jsx")
Proteins.evalJsxFolder("C:\\Program Files (x86)\\Common Files\\Adobe\\CEP\\extensions\\UI-DNA\\JSX\\Proteins_libs")

//--------------------------


//Kinase.layer.creatNewShapeLayerSquarenss_ByActive("2122121",{fillColor:{r:255,g:0,b:12},w:60, h:100,lineWidth: 10})
Kinase.layer.setLayerToSmart_ByActive()

//EnzJSX.setLayerInfo_shape_byId  ({"lineWidth":"10"}, 417)
//EnzJSX.setLayerInfo_shape_byId  ({"fillColorEnabled":false}, 390)
 // var ob = Kinase.layer.getLayerInfoObject_byActiveLayer()
 //var ob =Kinase.layer.getLayerEffectsObject(Kinase.REF_ActiveLayer, null)
  //    var ob = Kinase.layer.get_XXX_Objcet(Kinase.REF_ActiveLayer, null, "layerEffects")

//var ob = Kinase.layer.getLayerInfoObject_byActiveLayer ()



//EnzJSX.setLayerInfo_more_byId({"visible":false} ,420 )

///  ob=Kinase.layer.getEffectsList_universal (ob,"dropShadow")
//EnzJSX.setLayerInfo_quickEffect_byId({"dropShadow":{"color":{"r":79,"g":219,"b":95}}} ,423 )
 //typeof EnzJSX.getSelectLayerArray

//log(ob)
//log(json(ob))