var idMk = charIDToTypeID( "Mk  " );
var desc8 = new ActionDescriptor();
var idNw = charIDToTypeID( "Nw  " );
var idChnl = charIDToTypeID( "Chnl" );
desc8.putClass( idNw, idChnl );
var idUsng = charIDToTypeID( "Usng" );
var desc9 = new ActionDescriptor();
var idT = charIDToTypeID( "T   " );
var ref2 = new ActionReference();
var idChnl = charIDToTypeID( "Chnl" );
var idChnl = charIDToTypeID( "Chnl" );
var idRd = charIDToTypeID( "Rd  " );
ref2.putEnumerated( idChnl, idChnl, idRd );
var idLyr = charIDToTypeID( "Lyr " );
var idOrdn = charIDToTypeID( "Ordn" );
var idMrgd = charIDToTypeID( "Mrgd" );
ref2.putEnumerated( idLyr, idOrdn, idMrgd );
desc9.putReference( idT, ref2 );
var idClcl = charIDToTypeID( "Clcl" );
var idClcn = charIDToTypeID( "Clcn" );
var idMltp = charIDToTypeID( "Mltp" );
desc9.putEnumerated( idClcl, idClcn, idMltp );
var idSrctwo = charIDToTypeID( "Src2" );
var ref3 = new ActionReference();
var idChnl = charIDToTypeID( "Chnl" );
var idChnl = charIDToTypeID( "Chnl" );
var idRd = charIDToTypeID( "Rd  " );
ref3.putEnumerated( idChnl, idChnl, idRd );
desc9.putReference( idSrctwo, ref3 );
var idClcl = charIDToTypeID( "Clcl" );
desc8.putObject( idUsng, idClcl, desc9 );
executeAction( idMk, desc8, DialogModes.NO );