$.evalFile("E:/Work/GitHub/UI-DNA/DVE/bin/JSX/json3.js")
$.evalFile("E:/Work/GitHub/UI-DNA/DVE/Enzymes/test/test.jsx")

var idMk = charIDToTypeID( "Mk  " );
    var desc3422 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref722 = new ActionReference();
        var idcontentLayer = stringIDToTypeID( "contentLayer" );
        ref722.putClass( idcontentLayer );
    desc3422.putReference( idnull, ref722 );
    var idUsng = charIDToTypeID( "Usng" );
        var desc3423 = new ActionDescriptor();
        var idType = charIDToTypeID( "Type" );
            var desc3424 = new ActionDescriptor();
            var idClr = charIDToTypeID( "Clr " );
                var desc3425 = new ActionDescriptor();
                var idRd = charIDToTypeID( "Rd  " );
                desc3425.putDouble( idRd, 31.003418 );
                var idGrn = charIDToTypeID( "Grn " );
                desc3425.putDouble( idGrn, 51.999207 );
                var idBl = charIDToTypeID( "Bl  " );
                desc3425.putDouble( idBl, 137.997894 );
            var idRGBC = charIDToTypeID( "RGBC" );
            desc3424.putObject( idClr, idRGBC, desc3425 );
        var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
        desc3423.putObject( idType, idsolidColorLayer, desc3424 );
        var idShp = charIDToTypeID( "Shp " );
            var desc3426 = new ActionDescriptor();
            var idunitValueQuadVersion = stringIDToTypeID( "unitValueQuadVersion" );
            desc3426.putInteger( idunitValueQuadVersion, 1 );
            var idTop = charIDToTypeID( "Top " );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idTop, idPxl, 33.000000 );
            var idLeft = charIDToTypeID( "Left" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idLeft, idPxl, 210.000000 );
            var idBtom = charIDToTypeID( "Btom" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idBtom, idPxl, 49.000000 );
            var idRght = charIDToTypeID( "Rght" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idRght, idPxl, 256.000000 );
            var idtopRight = stringIDToTypeID( "topRight" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idtopRight, idPxl, 3.000000 );
            var idtopLeft = stringIDToTypeID( "topLeft" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idtopLeft, idPxl, 3.000000 );
            var idbottomLeft = stringIDToTypeID( "bottomLeft" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idbottomLeft, idPxl, 3.000000 );
            var idbottomRight = stringIDToTypeID( "bottomRight" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3426.putUnitDouble( idbottomRight, idPxl, 3.000000 );
        var idRctn = charIDToTypeID( "Rctn" );
        desc3423.putObject( idShp, idRctn, desc3426 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
            var desc3427 = new ActionDescriptor();
            var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
            desc3427.putInteger( idstrokeStyleVersion, 2 );
            var idstrokeEnabled = stringIDToTypeID( "strokeEnabled" );
            desc3427.putBoolean( idstrokeEnabled, true );
            var idfillEnabled = stringIDToTypeID( "fillEnabled" );
            desc3427.putBoolean( idfillEnabled, true );
            var idstrokeStyleLineWidth = stringIDToTypeID( "strokeStyleLineWidth" );
            var idPxl = charIDToTypeID( "#Pxl" );
            desc3427.putUnitDouble( idstrokeStyleLineWidth, idPxl, 1.000000 );
            var idstrokeStyleLineDashOffset = stringIDToTypeID( "strokeStyleLineDashOffset" );
            var idPnt = charIDToTypeID( "#Pnt" );
            desc3427.putUnitDouble( idstrokeStyleLineDashOffset, idPnt, 0.000000 );
            var idstrokeStyleMiterLimit = stringIDToTypeID( "strokeStyleMiterLimit" );
            desc3427.putDouble( idstrokeStyleMiterLimit, 100.000000 );
            var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
            var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
            var idstrokeStyleButtCap = stringIDToTypeID( "strokeStyleButtCap" );
            desc3427.putEnumerated( idstrokeStyleLineCapType, idstrokeStyleLineCapType, idstrokeStyleButtCap );
            var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
            var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
            var idstrokeStyleMiterJoin = stringIDToTypeID( "strokeStyleMiterJoin" );
            desc3427.putEnumerated( idstrokeStyleLineJoinType, idstrokeStyleLineJoinType, idstrokeStyleMiterJoin );
            var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
            var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
            var idstrokeStyleAlignInside = stringIDToTypeID( "strokeStyleAlignInside" );
            desc3427.putEnumerated( idstrokeStyleLineAlignment, idstrokeStyleLineAlignment, idstrokeStyleAlignInside );
            var idstrokeStyleScaleLock = stringIDToTypeID( "strokeStyleScaleLock" );
            desc3427.putBoolean( idstrokeStyleScaleLock, false );
            var idstrokeStyleStrokeAdjust = stringIDToTypeID( "strokeStyleStrokeAdjust" );
            desc3427.putBoolean( idstrokeStyleStrokeAdjust, false );
            var idstrokeStyleLineDashSet = stringIDToTypeID( "strokeStyleLineDashSet" );
                var list506 = new ActionList();
            desc3427.putList( idstrokeStyleLineDashSet, list506 );
            var idstrokeStyleBlendMode = stringIDToTypeID( "strokeStyleBlendMode" );
            var idBlnM = charIDToTypeID( "BlnM" );
            var idNrml = charIDToTypeID( "Nrml" );
            desc3427.putEnumerated( idstrokeStyleBlendMode, idBlnM, idNrml );
            var idstrokeStyleOpacity = stringIDToTypeID( "strokeStyleOpacity" );
            var idPrc = charIDToTypeID( "#Prc" );
            desc3427.putUnitDouble( idstrokeStyleOpacity, idPrc, 100.000000 );
            var idstrokeStyleContent = stringIDToTypeID( "strokeStyleContent" );
                var desc3428 = new ActionDescriptor();
                var idClr = charIDToTypeID( "Clr " );
                    var desc3429 = new ActionDescriptor();
                    var idRd = charIDToTypeID( "Rd  " );
                    desc3429.putDouble( idRd, 157.000006 );
                    var idGrn = charIDToTypeID( "Grn " );
                    desc3429.putDouble( idGrn, 157.000006 );
                    var idBl = charIDToTypeID( "Bl  " );
                    desc3429.putDouble( idBl, 157.000006 );
                var idRGBC = charIDToTypeID( "RGBC" );
                desc3428.putObject( idClr, idRGBC, desc3429 );
            var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
            desc3427.putObject( idstrokeStyleContent, idsolidColorLayer, desc3428 );
            var idstrokeStyleResolution = stringIDToTypeID( "strokeStyleResolution" );
            desc3427.putDouble( idstrokeStyleResolution, 96.000000 );
        var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
        desc3423.putObject( idstrokeStyle, idstrokeStyle, desc3427 );
    var idcontentLayer = stringIDToTypeID( "contentLayer" );
    desc3422.putObject( idUsng, idcontentLayer, desc3423 );
    var idLyrI = charIDToTypeID( "LyrI" );
    desc3422.putInteger( idLyrI, 79 );


json( mu.actionDescriptorToObject(desc3422))