$.evalFile(File($.fileName).path + "/test.jsx")




task_objectToActionDescriptor();
task_objectToActionReference();
logSave();


// task --------


function task_objectToActionReference()
{
    log("[task]-objectToActionReference--------");

    // ActionReference 转 Object 再到 JSON---------------------------------
    // ActionReference -> Object -> JSON
    log("1. ActionReference 转 Object 再到 JSON");
    var ref50 = new ActionReference();
    var idPrpr = charIDToTypeID("Prpr");
    var idLefx = charIDToTypeID("Lefx");
    ref50.putProperty(idPrpr, idLefx);
    var idLyr = charIDToTypeID("Lyr ");
    var idOrdn = charIDToTypeID("Ordn");
    var idTrgt = charIDToTypeID("Trgt");
    ref50.putEnumerated(idLyr, idOrdn, idTrgt);
    obo_af(ref50)

    var ref50  = new ActionReference();
    var idLyr = charIDToTypeID( "Lyr " );
    ref50 .putName( idLyr, "图层 2" );
    obo_af(ref50)

}








function task_objectToActionDescriptor()
{
    log("[task]-objectToActionDescriptor--------");
    //创建一个矩形图层---------------------------------
    // ActionDescriptor -> Object -> ActionDescriptor -> executeAction()
    log("1. 创建一个矩形图层");

    var idMk = charIDToTypeID( "Mk  " );
    var desc597 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
    var ref153 = new ActionReference();
    var idcontentLayer = stringIDToTypeID( "contentLayer" );
    ref153.putClass( idcontentLayer );
    desc597.putReference( idnull, ref153 );
    var idUsng = charIDToTypeID( "Usng" );
    var desc598 = new ActionDescriptor();
    var idType = charIDToTypeID( "Type" );
    var desc599 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc600 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc600.putDouble( idRd, 68.392105 );
    var idGrn = charIDToTypeID( "Grn " );
    desc600.putDouble( idGrn, 137.781245 );
    var idBl = charIDToTypeID( "Bl  " );
    desc600.putDouble( idBl, 201.557221 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc599.putObject( idClr, idRGBC, desc600 );
    var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
    desc598.putObject( idType, idsolidColorLayer, desc599 );
    var idShp = charIDToTypeID( "Shp " );
    var desc601 = new ActionDescriptor();
    var idunitValueQuadVersion = stringIDToTypeID( "unitValueQuadVersion" );
    desc601.putInteger( idunitValueQuadVersion, 1 );
    var idTop = charIDToTypeID( "Top " );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idTop, idPxl, 124.000000 );
    var idLeft = charIDToTypeID( "Left" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idLeft, idPxl, 154.000000 );
    var idBtom = charIDToTypeID( "Btom" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idBtom, idPxl, 544.000000 );
    var idRght = charIDToTypeID( "Rght" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idRght, idPxl, 882.000000 );
    var idtopRight = stringIDToTypeID( "topRight" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idtopRight, idPxl, 0.000000 );
    var idtopLeft = stringIDToTypeID( "topLeft" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idtopLeft, idPxl, 0.000000 );
    var idbottomLeft = stringIDToTypeID( "bottomLeft" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idbottomLeft, idPxl, 0.000000 );
    var idbottomRight = stringIDToTypeID( "bottomRight" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc601.putUnitDouble( idbottomRight, idPxl, 0.000000 );
    var idRctn = charIDToTypeID( "Rctn" );
    desc598.putObject( idShp, idRctn, desc601 );
    var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
    var desc602 = new ActionDescriptor();
    var idstrokeStyleVersion = stringIDToTypeID( "strokeStyleVersion" );
    desc602.putInteger( idstrokeStyleVersion, 2 );
    var idstrokeEnabled = stringIDToTypeID( "strokeEnabled" );
    desc602.putBoolean( idstrokeEnabled, true );
    var idfillEnabled = stringIDToTypeID( "fillEnabled" );
    desc602.putBoolean( idfillEnabled, true );
    var idstrokeStyleLineWidth = stringIDToTypeID( "strokeStyleLineWidth" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc602.putUnitDouble( idstrokeStyleLineWidth, idPxl, 1.000000 );
    var idstrokeStyleLineDashOffset = stringIDToTypeID( "strokeStyleLineDashOffset" );
    var idPnt = charIDToTypeID( "#Pnt" );
    desc602.putUnitDouble( idstrokeStyleLineDashOffset, idPnt, 0.000000 );
    var idstrokeStyleMiterLimit = stringIDToTypeID( "strokeStyleMiterLimit" );
    desc602.putDouble( idstrokeStyleMiterLimit, 100.000000 );
    var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
    var idstrokeStyleLineCapType = stringIDToTypeID( "strokeStyleLineCapType" );
    var idstrokeStyleButtCap = stringIDToTypeID( "strokeStyleButtCap" );
    desc602.putEnumerated( idstrokeStyleLineCapType, idstrokeStyleLineCapType, idstrokeStyleButtCap );
    var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
    var idstrokeStyleLineJoinType = stringIDToTypeID( "strokeStyleLineJoinType" );
    var idstrokeStyleMiterJoin = stringIDToTypeID( "strokeStyleMiterJoin" );
    desc602.putEnumerated( idstrokeStyleLineJoinType, idstrokeStyleLineJoinType, idstrokeStyleMiterJoin );
    var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
    var idstrokeStyleLineAlignment = stringIDToTypeID( "strokeStyleLineAlignment" );
    var idstrokeStyleAlignInside = stringIDToTypeID( "strokeStyleAlignInside" );
    desc602.putEnumerated( idstrokeStyleLineAlignment, idstrokeStyleLineAlignment, idstrokeStyleAlignInside );
    var idstrokeStyleScaleLock = stringIDToTypeID( "strokeStyleScaleLock" );
    desc602.putBoolean( idstrokeStyleScaleLock, false );
    var idstrokeStyleStrokeAdjust = stringIDToTypeID( "strokeStyleStrokeAdjust" );
    desc602.putBoolean( idstrokeStyleStrokeAdjust, false );
    var idstrokeStyleLineDashSet = stringIDToTypeID( "strokeStyleLineDashSet" );
    var list98 = new ActionList();
    desc602.putList( idstrokeStyleLineDashSet, list98 );
    var idstrokeStyleBlendMode = stringIDToTypeID( "strokeStyleBlendMode" );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc602.putEnumerated( idstrokeStyleBlendMode, idBlnM, idNrml );
    var idstrokeStyleOpacity = stringIDToTypeID( "strokeStyleOpacity" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc602.putUnitDouble( idstrokeStyleOpacity, idPrc, 100.000000 );
    var idstrokeStyleContent = stringIDToTypeID( "strokeStyleContent" );
    var desc603 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc604 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc604.putDouble( idRd, 157.000006 );
    var idGrn = charIDToTypeID( "Grn " );
    desc604.putDouble( idGrn, 157.000006 );
    var idBl = charIDToTypeID( "Bl  " );
    desc604.putDouble( idBl, 157.000006 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc603.putObject( idClr, idRGBC, desc604 );
    var idsolidColorLayer = stringIDToTypeID( "solidColorLayer" );
    desc602.putObject( idstrokeStyleContent, idsolidColorLayer, desc603 );
    var idstrokeStyleResolution = stringIDToTypeID( "strokeStyleResolution" );
    desc602.putDouble( idstrokeStyleResolution, 72.000000 );
    var idstrokeStyle = stringIDToTypeID( "strokeStyle" );
    desc598.putObject( idstrokeStyle, idstrokeStyle, desc602 );
    var idcontentLayer = stringIDToTypeID( "contentLayer" );
    desc597.putObject( idUsng, idcontentLayer, desc598 );
    var idLyrI = charIDToTypeID( "LyrI" );
    desc597.putInteger( idLyrI, 6 );

    var ob = mu.actionDescriptorToObject(desc597);
    var ad = mu.objectToActionDescriptor(ob);
    executeAction( idMk, ad, DialogModes.NO );




    //设置图层样式---------------------------------
    // ActionDescriptor -> Object -> ActionDescriptor -> executeAction()
    log("2. 设置图层样式");

    var idsetd = charIDToTypeID( "setd" );
    var desc631 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
    var ref159 = new ActionReference();
    var idPrpr = charIDToTypeID( "Prpr" );
    var idLefx = charIDToTypeID( "Lefx" );
    ref159.putProperty( idPrpr, idLefx );
    var idLyr = charIDToTypeID( "Lyr " );
    var idOrdn = charIDToTypeID( "Ordn" );
    var idTrgt = charIDToTypeID( "Trgt" );
    ref159.putEnumerated( idLyr, idOrdn, idTrgt );
    desc631.putReference( idnull, ref159 );
    var idT = charIDToTypeID( "T   " );
    var desc632 = new ActionDescriptor();
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc632.putUnitDouble( idScl, idPrc, 100.000000 );
    var iddropShadowMulti = stringIDToTypeID( "dropShadowMulti" );
    var list103 = new ActionList();
    var desc633 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc633.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc633.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc633.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc633.putEnumerated( idMd, idBlnM, idNrml );
    var idClr = charIDToTypeID( "Clr " );
    var desc634 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc634.putDouble( idRd, 255.000000 );
    var idGrn = charIDToTypeID( "Grn " );
    desc634.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc634.putDouble( idBl, 0.023346 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc633.putObject( idClr, idRGBC, desc634 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc633.putUnitDouble( idOpct, idPrc, 71.000000 );
    var iduglg = charIDToTypeID( "uglg" );
    desc633.putBoolean( iduglg, false );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc633.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc633.putUnitDouble( idDstn, idPxl, 13.000000 );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc633.putUnitDouble( idCkmt, idPxl, 1.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc633.putUnitDouble( idblur, idPxl, 10.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc633.putUnitDouble( idNose, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc633.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc635 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc635.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc633.putObject( idTrnS, idShpC, desc635 );
    var idlayerConceals = stringIDToTypeID( "layerConceals" );
    desc633.putBoolean( idlayerConceals, true );
    var idDrSh = charIDToTypeID( "DrSh" );
    list103.putObject( idDrSh, desc633 );
    var desc636 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc636.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc636.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc636.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc636.putEnumerated( idMd, idBlnM, idNrml );
    var idClr = charIDToTypeID( "Clr " );
    var desc637 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc637.putDouble( idRd, 96.571985 );
    var idGrn = charIDToTypeID( "Grn " );
    desc637.putDouble( idGrn, 255.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc637.putDouble( idBl, 54.000001 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc636.putObject( idClr, idRGBC, desc637 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc636.putUnitDouble( idOpct, idPrc, 71.000000 );
    var iduglg = charIDToTypeID( "uglg" );
    desc636.putBoolean( iduglg, false );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc636.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc636.putUnitDouble( idDstn, idPxl, 28.000000 );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc636.putUnitDouble( idCkmt, idPxl, 1.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc636.putUnitDouble( idblur, idPxl, 18.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc636.putUnitDouble( idNose, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc636.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc638 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc638.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc636.putObject( idTrnS, idShpC, desc638 );
    var idlayerConceals = stringIDToTypeID( "layerConceals" );
    desc636.putBoolean( idlayerConceals, true );
    var idDrSh = charIDToTypeID( "DrSh" );
    list103.putObject( idDrSh, desc636 );
    var desc639 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc639.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc639.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc639.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc639.putEnumerated( idMd, idBlnM, idNrml );
    var idClr = charIDToTypeID( "Clr " );
    var desc640 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc640.putDouble( idRd, 255.000000 );
    var idGrn = charIDToTypeID( "Grn " );
    desc640.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc640.putDouble( idBl, 0.023346 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc639.putObject( idClr, idRGBC, desc640 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc639.putUnitDouble( idOpct, idPrc, 71.000000 );
    var iduglg = charIDToTypeID( "uglg" );
    desc639.putBoolean( iduglg, false );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc639.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc639.putUnitDouble( idDstn, idPxl, 13.000000 );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc639.putUnitDouble( idCkmt, idPxl, 1.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc639.putUnitDouble( idblur, idPxl, 10.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc639.putUnitDouble( idNose, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc639.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc641 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc641.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc639.putObject( idTrnS, idShpC, desc641 );
    var idlayerConceals = stringIDToTypeID( "layerConceals" );
    desc639.putBoolean( idlayerConceals, true );
    var idDrSh = charIDToTypeID( "DrSh" );
    list103.putObject( idDrSh, desc639 );
    var desc642 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc642.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc642.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc642.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc642.putEnumerated( idMd, idBlnM, idNrml );
    var idClr = charIDToTypeID( "Clr " );
    var desc643 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc643.putDouble( idRd, 73.000003 );
    var idGrn = charIDToTypeID( "Grn " );
    desc643.putDouble( idGrn, 73.000003 );
    var idBl = charIDToTypeID( "Bl  " );
    desc643.putDouble( idBl, 73.000003 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc642.putObject( idClr, idRGBC, desc643 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc642.putUnitDouble( idOpct, idPrc, 68.000000 );
    var iduglg = charIDToTypeID( "uglg" );
    desc642.putBoolean( iduglg, false );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc642.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc642.putUnitDouble( idDstn, idPxl, 13.000000 );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc642.putUnitDouble( idCkmt, idPxl, 1.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc642.putUnitDouble( idblur, idPxl, 10.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc642.putUnitDouble( idNose, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc642.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc644 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc644.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc642.putObject( idTrnS, idShpC, desc644 );
    var idlayerConceals = stringIDToTypeID( "layerConceals" );
    desc642.putBoolean( idlayerConceals, true );
    var idDrSh = charIDToTypeID( "DrSh" );
    list103.putObject( idDrSh, desc642 );
    desc632.putList( iddropShadowMulti, list103 );
    var idinnerShadowMulti = stringIDToTypeID( "innerShadowMulti" );
    var list104 = new ActionList();
    var desc645 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc645.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc645.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc645.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idlinearLight = stringIDToTypeID( "linearLight" );
    desc645.putEnumerated( idMd, idBlnM, idlinearLight );
    var idClr = charIDToTypeID( "Clr " );
    var desc646 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc646.putDouble( idRd, 3.534862 );
    var idGrn = charIDToTypeID( "Grn " );
    desc646.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc646.putDouble( idBl, 0.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc645.putObject( idClr, idRGBC, desc646 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc645.putUnitDouble( idOpct, idPrc, 14.000000 );
    var iduglg = charIDToTypeID( "uglg" );
    desc645.putBoolean( iduglg, false );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc645.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc645.putUnitDouble( idDstn, idPxl, 3.000000 );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc645.putUnitDouble( idCkmt, idPxl, 0.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc645.putUnitDouble( idblur, idPxl, 2.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc645.putUnitDouble( idNose, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc645.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc647 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc647.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc645.putObject( idTrnS, idShpC, desc647 );
    var idIrSh = charIDToTypeID( "IrSh" );
    list104.putObject( idIrSh, desc645 );
    var desc648 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc648.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc648.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc648.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idlinearLight = stringIDToTypeID( "linearLight" );
    desc648.putEnumerated( idMd, idBlnM, idlinearLight );
    var idClr = charIDToTypeID( "Clr " );
    var desc649 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc649.putDouble( idRd, 3.534862 );
    var idGrn = charIDToTypeID( "Grn " );
    desc649.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc649.putDouble( idBl, 0.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc648.putObject( idClr, idRGBC, desc649 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc648.putUnitDouble( idOpct, idPrc, 14.000000 );
    var iduglg = charIDToTypeID( "uglg" );
    desc648.putBoolean( iduglg, false );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc648.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc648.putUnitDouble( idDstn, idPxl, 3.000000 );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc648.putUnitDouble( idCkmt, idPxl, 0.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc648.putUnitDouble( idblur, idPxl, 2.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc648.putUnitDouble( idNose, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc648.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc650 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc650.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc648.putObject( idTrnS, idShpC, desc650 );
    var idIrSh = charIDToTypeID( "IrSh" );
    list104.putObject( idIrSh, desc648 );
    desc632.putList( idinnerShadowMulti, list104 );
    var idsolidFillMulti = stringIDToTypeID( "solidFillMulti" );
    var list105 = new ActionList();
    var desc651 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc651.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc651.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc651.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc651.putEnumerated( idMd, idBlnM, idNrml );
    var idClr = charIDToTypeID( "Clr " );
    var desc652 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc652.putDouble( idRd, 147.000006 );
    var idGrn = charIDToTypeID( "Grn " );
    desc652.putDouble( idGrn, 147.000006 );
    var idBl = charIDToTypeID( "Bl  " );
    desc652.putDouble( idBl, 147.000006 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc651.putObject( idClr, idRGBC, desc652 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc651.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idSoFi = charIDToTypeID( "SoFi" );
    list105.putObject( idSoFi, desc651 );
    var desc653 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc653.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc653.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc653.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc653.putEnumerated( idMd, idBlnM, idNrml );
    var idClr = charIDToTypeID( "Clr " );
    var desc654 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc654.putDouble( idRd, 147.000006 );
    var idGrn = charIDToTypeID( "Grn " );
    desc654.putDouble( idGrn, 147.000006 );
    var idBl = charIDToTypeID( "Bl  " );
    desc654.putDouble( idBl, 147.000006 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc653.putObject( idClr, idRGBC, desc654 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc653.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idSoFi = charIDToTypeID( "SoFi" );
    list105.putObject( idSoFi, desc653 );
    desc632.putList( idsolidFillMulti, list105 );
    var idgradientFillMulti = stringIDToTypeID( "gradientFillMulti" );
    var list106 = new ActionList();
    var desc655 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc655.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc655.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc655.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc655.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc655.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idGrad = charIDToTypeID( "Grad" );
    var desc656 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc656.putString( idNm, """自定""" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idCstS = charIDToTypeID( "CstS" );
    desc656.putEnumerated( idGrdF, idGrdF, idCstS );
    var idIntr = charIDToTypeID( "Intr" );
    desc656.putDouble( idIntr, 4096.000000 );
    var idClrs = charIDToTypeID( "Clrs" );
    var list107 = new ActionList();
    var desc657 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc658 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc658.putDouble( idRd, 43.999329 );
    var idGrn = charIDToTypeID( "Grn " );
    desc658.putDouble( idGrn, 251.000061 );
    var idBl = charIDToTypeID( "Bl  " );
    desc658.putDouble( idBl, 243.996277 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc657.putObject( idClr, idRGBC, desc658 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc657.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc657.putInteger( idLctn, 32 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc657.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list107.putObject( idClrt, desc657 );
    var desc659 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc660 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc660.putDouble( idRd, 33.999481 );
    var idGrn = charIDToTypeID( "Grn " );
    desc660.putDouble( idGrn, 213.996735 );
    var idBl = charIDToTypeID( "Bl  " );
    desc660.putDouble( idBl, 253.000031 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc659.putObject( idClr, idRGBC, desc660 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc659.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc659.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc659.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list107.putObject( idClrt, desc659 );
    desc656.putList( idClrs, list107 );
    var idTrns = charIDToTypeID( "Trns" );
    var list108 = new ActionList();
    var desc661 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc661.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc661.putInteger( idLctn, 0 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc661.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list108.putObject( idTrnS, desc661 );
    var desc662 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc662.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc662.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc662.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list108.putObject( idTrnS, desc662 );
    desc656.putList( idTrns, list108 );
    var idGrdn = charIDToTypeID( "Grdn" );
    desc655.putObject( idGrad, idGrdn, desc656 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc655.putUnitDouble( idAngl, idAng, 157.000000 );
    var idType = charIDToTypeID( "Type" );
    var idGrdT = charIDToTypeID( "GrdT" );
    var idLnr = charIDToTypeID( "Lnr " );
    desc655.putEnumerated( idType, idGrdT, idLnr );
    var idRvrs = charIDToTypeID( "Rvrs" );
    desc655.putBoolean( idRvrs, false );
    var idDthr = charIDToTypeID( "Dthr" );
    desc655.putBoolean( idDthr, false );
    var idAlgn = charIDToTypeID( "Algn" );
    desc655.putBoolean( idAlgn, true );
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc655.putUnitDouble( idScl, idPrc, 150.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    var desc663 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc663.putUnitDouble( idHrzn, idPrc, -27.274848 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc663.putUnitDouble( idVrtc, idPrc, -40.578075 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc655.putObject( idOfst, idPnt, desc663 );
    var idGrFl = charIDToTypeID( "GrFl" );
    list106.putObject( idGrFl, desc655 );
    var desc664 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc664.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc664.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc664.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc664.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc664.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idGrad = charIDToTypeID( "Grad" );
    var desc665 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc665.putString( idNm, """自定""" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idCstS = charIDToTypeID( "CstS" );
    desc665.putEnumerated( idGrdF, idGrdF, idCstS );
    var idIntr = charIDToTypeID( "Intr" );
    desc665.putDouble( idIntr, 4096.000000 );
    var idClrs = charIDToTypeID( "Clrs" );
    var list109 = new ActionList();
    var desc666 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc667 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc667.putDouble( idRd, 43.999329 );
    var idGrn = charIDToTypeID( "Grn " );
    desc667.putDouble( idGrn, 251.000061 );
    var idBl = charIDToTypeID( "Bl  " );
    desc667.putDouble( idBl, 243.996277 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc666.putObject( idClr, idRGBC, desc667 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc666.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc666.putInteger( idLctn, 32 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc666.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list109.putObject( idClrt, desc666 );
    var desc668 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc669 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc669.putDouble( idRd, 33.999481 );
    var idGrn = charIDToTypeID( "Grn " );
    desc669.putDouble( idGrn, 213.996735 );
    var idBl = charIDToTypeID( "Bl  " );
    desc669.putDouble( idBl, 253.000031 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc668.putObject( idClr, idRGBC, desc669 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc668.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc668.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc668.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list109.putObject( idClrt, desc668 );
    desc665.putList( idClrs, list109 );
    var idTrns = charIDToTypeID( "Trns" );
    var list110 = new ActionList();
    var desc670 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc670.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc670.putInteger( idLctn, 0 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc670.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list110.putObject( idTrnS, desc670 );
    var desc671 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc671.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc671.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc671.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list110.putObject( idTrnS, desc671 );
    desc665.putList( idTrns, list110 );
    var idGrdn = charIDToTypeID( "Grdn" );
    desc664.putObject( idGrad, idGrdn, desc665 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc664.putUnitDouble( idAngl, idAng, 157.000000 );
    var idType = charIDToTypeID( "Type" );
    var idGrdT = charIDToTypeID( "GrdT" );
    var idLnr = charIDToTypeID( "Lnr " );
    desc664.putEnumerated( idType, idGrdT, idLnr );
    var idRvrs = charIDToTypeID( "Rvrs" );
    desc664.putBoolean( idRvrs, false );
    var idDthr = charIDToTypeID( "Dthr" );
    desc664.putBoolean( idDthr, false );
    var idAlgn = charIDToTypeID( "Algn" );
    desc664.putBoolean( idAlgn, true );
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc664.putUnitDouble( idScl, idPrc, 150.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    var desc672 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc672.putUnitDouble( idHrzn, idPrc, -27.274848 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc672.putUnitDouble( idVrtc, idPrc, -40.578075 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc664.putObject( idOfst, idPnt, desc672 );
    var idGrFl = charIDToTypeID( "GrFl" );
    list106.putObject( idGrFl, desc664 );
    var desc673 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc673.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc673.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc673.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc673.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc673.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idGrad = charIDToTypeID( "Grad" );
    var desc674 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc674.putString( idNm, """自定""" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idCstS = charIDToTypeID( "CstS" );
    desc674.putEnumerated( idGrdF, idGrdF, idCstS );
    var idIntr = charIDToTypeID( "Intr" );
    desc674.putDouble( idIntr, 4096.000000 );
    var idClrs = charIDToTypeID( "Clrs" );
    var list111 = new ActionList();
    var desc675 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc676 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc676.putDouble( idRd, 43.999329 );
    var idGrn = charIDToTypeID( "Grn " );
    desc676.putDouble( idGrn, 251.000061 );
    var idBl = charIDToTypeID( "Bl  " );
    desc676.putDouble( idBl, 243.996277 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc675.putObject( idClr, idRGBC, desc676 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc675.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc675.putInteger( idLctn, 32 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc675.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list111.putObject( idClrt, desc675 );
    var desc677 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc678 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc678.putDouble( idRd, 33.999481 );
    var idGrn = charIDToTypeID( "Grn " );
    desc678.putDouble( idGrn, 213.996735 );
    var idBl = charIDToTypeID( "Bl  " );
    desc678.putDouble( idBl, 253.000031 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc677.putObject( idClr, idRGBC, desc678 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc677.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc677.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc677.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list111.putObject( idClrt, desc677 );
    desc674.putList( idClrs, list111 );
    var idTrns = charIDToTypeID( "Trns" );
    var list112 = new ActionList();
    var desc679 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc679.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc679.putInteger( idLctn, 0 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc679.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list112.putObject( idTrnS, desc679 );
    var desc680 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc680.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc680.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc680.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list112.putObject( idTrnS, desc680 );
    desc674.putList( idTrns, list112 );
    var idGrdn = charIDToTypeID( "Grdn" );
    desc673.putObject( idGrad, idGrdn, desc674 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc673.putUnitDouble( idAngl, idAng, 157.000000 );
    var idType = charIDToTypeID( "Type" );
    var idGrdT = charIDToTypeID( "GrdT" );
    var idLnr = charIDToTypeID( "Lnr " );
    desc673.putEnumerated( idType, idGrdT, idLnr );
    var idRvrs = charIDToTypeID( "Rvrs" );
    desc673.putBoolean( idRvrs, false );
    var idDthr = charIDToTypeID( "Dthr" );
    desc673.putBoolean( idDthr, false );
    var idAlgn = charIDToTypeID( "Algn" );
    desc673.putBoolean( idAlgn, true );
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc673.putUnitDouble( idScl, idPrc, 150.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    var desc681 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc681.putUnitDouble( idHrzn, idPrc, -27.274848 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc681.putUnitDouble( idVrtc, idPrc, -40.578075 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc673.putObject( idOfst, idPnt, desc681 );
    var idGrFl = charIDToTypeID( "GrFl" );
    list106.putObject( idGrFl, desc673 );
    var desc682 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc682.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc682.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc682.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc682.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc682.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idGrad = charIDToTypeID( "Grad" );
    var desc683 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc683.putString( idNm, """自定""" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idGrdF = charIDToTypeID( "GrdF" );
    var idCstS = charIDToTypeID( "CstS" );
    desc683.putEnumerated( idGrdF, idGrdF, idCstS );
    var idIntr = charIDToTypeID( "Intr" );
    desc683.putDouble( idIntr, 4096.000000 );
    var idClrs = charIDToTypeID( "Clrs" );
    var list113 = new ActionList();
    var desc684 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc685 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc685.putDouble( idRd, 78.000003 );
    var idGrn = charIDToTypeID( "Grn " );
    desc685.putDouble( idGrn, 211.280154 );
    var idBl = charIDToTypeID( "Bl  " );
    desc685.putDouble( idBl, 255.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc684.putObject( idClr, idRGBC, desc685 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc684.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc684.putInteger( idLctn, 0 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc684.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list113.putObject( idClrt, desc684 );
    var desc686 = new ActionDescriptor();
    var idClr = charIDToTypeID( "Clr " );
    var desc687 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc687.putDouble( idRd, 61.000000 );
    var idGrn = charIDToTypeID( "Grn " );
    desc687.putDouble( idGrn, 255.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc687.putDouble( idBl, 252.712067 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc686.putObject( idClr, idRGBC, desc687 );
    var idType = charIDToTypeID( "Type" );
    var idClry = charIDToTypeID( "Clry" );
    var idUsrS = charIDToTypeID( "UsrS" );
    desc686.putEnumerated( idType, idClry, idUsrS );
    var idLctn = charIDToTypeID( "Lctn" );
    desc686.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc686.putInteger( idMdpn, 50 );
    var idClrt = charIDToTypeID( "Clrt" );
    list113.putObject( idClrt, desc686 );
    desc683.putList( idClrs, list113 );
    var idTrns = charIDToTypeID( "Trns" );
    var list114 = new ActionList();
    var desc688 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc688.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc688.putInteger( idLctn, 0 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc688.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list114.putObject( idTrnS, desc688 );
    var desc689 = new ActionDescriptor();
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc689.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idLctn = charIDToTypeID( "Lctn" );
    desc689.putInteger( idLctn, 4096 );
    var idMdpn = charIDToTypeID( "Mdpn" );
    desc689.putInteger( idMdpn, 50 );
    var idTrnS = charIDToTypeID( "TrnS" );
    list114.putObject( idTrnS, desc689 );
    desc683.putList( idTrns, list114 );
    var idGrdn = charIDToTypeID( "Grdn" );
    desc682.putObject( idGrad, idGrdn, desc683 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc682.putUnitDouble( idAngl, idAng, 90.000000 );
    var idType = charIDToTypeID( "Type" );
    var idGrdT = charIDToTypeID( "GrdT" );
    var idLnr = charIDToTypeID( "Lnr " );
    desc682.putEnumerated( idType, idGrdT, idLnr );
    var idRvrs = charIDToTypeID( "Rvrs" );
    desc682.putBoolean( idRvrs, false );
    var idDthr = charIDToTypeID( "Dthr" );
    desc682.putBoolean( idDthr, false );
    var idAlgn = charIDToTypeID( "Algn" );
    desc682.putBoolean( idAlgn, true );
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc682.putUnitDouble( idScl, idPrc, 150.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    var desc690 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc690.putUnitDouble( idHrzn, idPrc, 14.489858 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc690.putUnitDouble( idVrtc, idPrc, -13.305347 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc682.putObject( idOfst, idPnt, desc690 );
    var idGrFl = charIDToTypeID( "GrFl" );
    list106.putObject( idGrFl, desc682 );
    desc632.putList( idgradientFillMulti, list106 );
    var idframeFXMulti = stringIDToTypeID( "frameFXMulti" );
    var list115 = new ActionList();
    var desc691 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc691.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc691.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc691.putBoolean( idshowInDialog, true );
    var idStyl = charIDToTypeID( "Styl" );
    var idFStl = charIDToTypeID( "FStl" );
    var idOutF = charIDToTypeID( "OutF" );
    desc691.putEnumerated( idStyl, idFStl, idOutF );
    var idPntT = charIDToTypeID( "PntT" );
    var idFrFl = charIDToTypeID( "FrFl" );
    var idSClr = charIDToTypeID( "SClr" );
    desc691.putEnumerated( idPntT, idFrFl, idSClr );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc691.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc691.putUnitDouble( idOpct, idPrc, 85.000000 );
    var idSz = charIDToTypeID( "Sz  " );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc691.putUnitDouble( idSz, idPxl, 2.000000 );
    var idClr = charIDToTypeID( "Clr " );
    var desc692 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc692.putDouble( idRd, 251.568100 );
    var idGrn = charIDToTypeID( "Grn " );
    desc692.putDouble( idGrn, 252.715958 );
    var idBl = charIDToTypeID( "Bl  " );
    desc692.putDouble( idBl, 255.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc691.putObject( idClr, idRGBC, desc692 );
    var idoverprint = stringIDToTypeID( "overprint" );
    desc691.putBoolean( idoverprint, false );
    var idFrFX = charIDToTypeID( "FrFX" );
    list115.putObject( idFrFX, desc691 );
    var desc693 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc693.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc693.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc693.putBoolean( idshowInDialog, true );
    var idStyl = charIDToTypeID( "Styl" );
    var idFStl = charIDToTypeID( "FStl" );
    var idOutF = charIDToTypeID( "OutF" );
    desc693.putEnumerated( idStyl, idFStl, idOutF );
    var idPntT = charIDToTypeID( "PntT" );
    var idFrFl = charIDToTypeID( "FrFl" );
    var idSClr = charIDToTypeID( "SClr" );
    desc693.putEnumerated( idPntT, idFrFl, idSClr );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc693.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc693.putUnitDouble( idOpct, idPrc, 85.000000 );
    var idSz = charIDToTypeID( "Sz  " );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc693.putUnitDouble( idSz, idPxl, 2.000000 );
    var idClr = charIDToTypeID( "Clr " );
    var desc694 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc694.putDouble( idRd, 251.568100 );
    var idGrn = charIDToTypeID( "Grn " );
    desc694.putDouble( idGrn, 252.715958 );
    var idBl = charIDToTypeID( "Bl  " );
    desc694.putDouble( idBl, 255.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc693.putObject( idClr, idRGBC, desc694 );
    var idoverprint = stringIDToTypeID( "overprint" );
    desc693.putBoolean( idoverprint, false );
    var idFrFX = charIDToTypeID( "FrFX" );
    list115.putObject( idFrFX, desc693 );
    var desc695 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc695.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc695.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc695.putBoolean( idshowInDialog, true );
    var idStyl = charIDToTypeID( "Styl" );
    var idFStl = charIDToTypeID( "FStl" );
    var idInsF = charIDToTypeID( "InsF" );
    desc695.putEnumerated( idStyl, idFStl, idInsF );
    var idPntT = charIDToTypeID( "PntT" );
    var idFrFl = charIDToTypeID( "FrFl" );
    var idSClr = charIDToTypeID( "SClr" );
    desc695.putEnumerated( idPntT, idFrFl, idSClr );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idNrml = charIDToTypeID( "Nrml" );
    desc695.putEnumerated( idMd, idBlnM, idNrml );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc695.putUnitDouble( idOpct, idPrc, 100.000000 );
    var idSz = charIDToTypeID( "Sz  " );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc695.putUnitDouble( idSz, idPxl, 1.000000 );
    var idClr = charIDToTypeID( "Clr " );
    var desc696 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc696.putDouble( idRd, 255.000000 );
    var idGrn = charIDToTypeID( "Grn " );
    desc696.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc696.putDouble( idBl, 0.023346 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc695.putObject( idClr, idRGBC, desc696 );
    var idoverprint = stringIDToTypeID( "overprint" );
    desc695.putBoolean( idoverprint, false );
    var idFrFX = charIDToTypeID( "FrFX" );
    list115.putObject( idFrFX, desc695 );
    desc632.putList( idframeFXMulti, list115 );
    var idOrGl = charIDToTypeID( "OrGl" );
    var desc697 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc697.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc697.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc697.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idScrn = charIDToTypeID( "Scrn" );
    desc697.putEnumerated( idMd, idBlnM, idScrn );
    var idClr = charIDToTypeID( "Clr " );
    var desc698 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc698.putDouble( idRd, 254.999985 );
    var idGrn = charIDToTypeID( "Grn " );
    desc698.putDouble( idGrn, 254.999939 );
    var idBl = charIDToTypeID( "Bl  " );
    desc698.putDouble( idBl, 254.999970 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc697.putObject( idClr, idRGBC, desc698 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc697.putUnitDouble( idOpct, idPrc, 35.000000 );
    var idGlwT = charIDToTypeID( "GlwT" );
    var idBETE = charIDToTypeID( "BETE" );
    var idSfBL = charIDToTypeID( "SfBL" );
    desc697.putEnumerated( idGlwT, idBETE, idSfBL );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc697.putUnitDouble( idCkmt, idPxl, 0.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc697.putUnitDouble( idblur, idPxl, 54.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc697.putUnitDouble( idNose, idPrc, 0.000000 );
    var idShdN = charIDToTypeID( "ShdN" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc697.putUnitDouble( idShdN, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc697.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc699 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc699.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc697.putObject( idTrnS, idShpC, desc699 );
    var idInpr = charIDToTypeID( "Inpr" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc697.putUnitDouble( idInpr, idPrc, 50.000000 );
    var idOrGl = charIDToTypeID( "OrGl" );
    desc632.putObject( idOrGl, idOrGl, desc697 );
    var idIrGl = charIDToTypeID( "IrGl" );
    var desc700 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc700.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc700.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc700.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idMltp = charIDToTypeID( "Mltp" );
    desc700.putEnumerated( idMd, idBlnM, idMltp );
    var idClr = charIDToTypeID( "Clr " );
    var desc701 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc701.putDouble( idRd, 3.534862 );
    var idGrn = charIDToTypeID( "Grn " );
    desc701.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc701.putDouble( idBl, 0.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc700.putObject( idClr, idRGBC, desc701 );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc700.putUnitDouble( idOpct, idPrc, 23.000000 );
    var idGlwT = charIDToTypeID( "GlwT" );
    var idBETE = charIDToTypeID( "BETE" );
    var idSfBL = charIDToTypeID( "SfBL" );
    desc700.putEnumerated( idGlwT, idBETE, idSfBL );
    var idCkmt = charIDToTypeID( "Ckmt" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc700.putUnitDouble( idCkmt, idPxl, 16.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc700.putUnitDouble( idblur, idPxl, 1.000000 );
    var idNose = charIDToTypeID( "Nose" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc700.putUnitDouble( idNose, idPrc, 64.000000 );
    var idShdN = charIDToTypeID( "ShdN" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc700.putUnitDouble( idShdN, idPrc, 0.000000 );
    var idAntA = charIDToTypeID( "AntA" );
    desc700.putBoolean( idAntA, false );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc702 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc702.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc700.putObject( idTrnS, idShpC, desc702 );
    var idInpr = charIDToTypeID( "Inpr" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc700.putUnitDouble( idInpr, idPrc, 50.000000 );
    var idglwS = charIDToTypeID( "glwS" );
    var idIGSr = charIDToTypeID( "IGSr" );
    var idSrcE = charIDToTypeID( "SrcE" );
    desc700.putEnumerated( idglwS, idIGSr, idSrcE );
    var idIrGl = charIDToTypeID( "IrGl" );
    desc632.putObject( idIrGl, idIrGl, desc700 );
    var idebbl = charIDToTypeID( "ebbl" );
    var desc703 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc703.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc703.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc703.putBoolean( idshowInDialog, true );
    var idhglM = charIDToTypeID( "hglM" );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idScrn = charIDToTypeID( "Scrn" );
    desc703.putEnumerated( idhglM, idBlnM, idScrn );
    var idhglC = charIDToTypeID( "hglC" );
    var desc704 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc704.putDouble( idRd, 254.999985 );
    var idGrn = charIDToTypeID( "Grn " );
    desc704.putDouble( idGrn, 254.999939 );
    var idBl = charIDToTypeID( "Bl  " );
    desc704.putDouble( idBl, 254.999970 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc703.putObject( idhglC, idRGBC, desc704 );
    var idhglO = charIDToTypeID( "hglO" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc703.putUnitDouble( idhglO, idPrc, 100.000000 );
    var idsdwM = charIDToTypeID( "sdwM" );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idMltp = charIDToTypeID( "Mltp" );
    desc703.putEnumerated( idsdwM, idBlnM, idMltp );
    var idsdwC = charIDToTypeID( "sdwC" );
    var desc705 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc705.putDouble( idRd, 3.534862 );
    var idGrn = charIDToTypeID( "Grn " );
    desc705.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc705.putDouble( idBl, 0.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc703.putObject( idsdwC, idRGBC, desc705 );
    var idsdwO = charIDToTypeID( "sdwO" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc703.putUnitDouble( idsdwO, idPrc, 100.000000 );
    var idbvlT = charIDToTypeID( "bvlT" );
    var idbvlT = charIDToTypeID( "bvlT" );
    var idPrBL = charIDToTypeID( "PrBL" );
    desc703.putEnumerated( idbvlT, idbvlT, idPrBL );
    var idbvlS = charIDToTypeID( "bvlS" );
    var idBESl = charIDToTypeID( "BESl" );
    var idOtrB = charIDToTypeID( "OtrB" );
    desc703.putEnumerated( idbvlS, idBESl, idOtrB );
    var iduglg = charIDToTypeID( "uglg" );
    desc703.putBoolean( iduglg, true );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc703.putUnitDouble( idlagl, idAng, 90.000000 );
    var idLald = charIDToTypeID( "Lald" );
    var idAng = charIDToTypeID( "#Ang" );
    desc703.putUnitDouble( idLald, idAng, 30.000000 );
    var idsrgR = charIDToTypeID( "srgR" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc703.putUnitDouble( idsrgR, idPrc, 1000.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc703.putUnitDouble( idblur, idPxl, 4.000000 );
    var idbvlD = charIDToTypeID( "bvlD" );
    var idBESs = charIDToTypeID( "BESs" );
    var idIn = charIDToTypeID( "In  " );
    desc703.putEnumerated( idbvlD, idBESs, idIn );
    var idTrnS = charIDToTypeID( "TrnS" );
    var desc706 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc706.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc703.putObject( idTrnS, idShpC, desc706 );
    var idantialiasGloss = stringIDToTypeID( "antialiasGloss" );
    desc703.putBoolean( idantialiasGloss, false );
    var idSftn = charIDToTypeID( "Sftn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc703.putUnitDouble( idSftn, idPxl, 0.000000 );
    var iduseShape = stringIDToTypeID( "useShape" );
    desc703.putBoolean( iduseShape, true );
    var idMpgS = charIDToTypeID( "MpgS" );
    var desc707 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc707.putString( idNm, """默认""" );
    var idCrv = charIDToTypeID( "Crv " );
    var list116 = new ActionList();
    var desc708 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    desc708.putDouble( idHrzn, 0.000000 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    desc708.putDouble( idVrtc, 0.000000 );
    var idCrPt = charIDToTypeID( "CrPt" );
    list116.putObject( idCrPt, desc708 );
    var desc709 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    desc709.putDouble( idHrzn, 255.000000 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    desc709.putDouble( idVrtc, 255.000000 );
    var idCrPt = charIDToTypeID( "CrPt" );
    list116.putObject( idCrPt, desc709 );
    desc707.putList( idCrv, list116 );
    var idShpC = charIDToTypeID( "ShpC" );
    desc703.putObject( idMpgS, idShpC, desc707 );
    var idAntA = charIDToTypeID( "AntA" );
    desc703.putBoolean( idAntA, false );
    var idInpr = charIDToTypeID( "Inpr" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc703.putUnitDouble( idInpr, idPrc, 100.000000 );
    var iduseTexture = stringIDToTypeID( "useTexture" );
    desc703.putBoolean( iduseTexture, true );
    var idInvT = charIDToTypeID( "InvT" );
    desc703.putBoolean( idInvT, false );
    var idAlgn = charIDToTypeID( "Algn" );
    desc703.putBoolean( idAlgn, true );
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc703.putUnitDouble( idScl, idPrc, 100.000000 );
    var idtextureDepth = stringIDToTypeID( "textureDepth" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc703.putUnitDouble( idtextureDepth, idPrc, 100.000000 );
    var idPtrn = charIDToTypeID( "Ptrn" );
    var desc710 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc710.putString( idNm, """$$$/Patterns/Defaults/Watercolor=Watercolor""" );
    var idIdnt = charIDToTypeID( "Idnt" );
    desc710.putString( idIdnt, """0836e93e-4438-11e6-92ca-e739c526f17b""" );
    var idPtrn = charIDToTypeID( "Ptrn" );
    desc703.putObject( idPtrn, idPtrn, desc710 );
    var idphase = stringIDToTypeID( "phase" );
    var desc711 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    desc711.putDouble( idHrzn, 0.000000 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    desc711.putDouble( idVrtc, 0.000000 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc703.putObject( idphase, idPnt, desc711 );
    var idebbl = charIDToTypeID( "ebbl" );
    desc632.putObject( idebbl, idebbl, desc703 );
    var idChFX = charIDToTypeID( "ChFX" );
    var desc712 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc712.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc712.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc712.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idMltp = charIDToTypeID( "Mltp" );
    desc712.putEnumerated( idMd, idBlnM, idMltp );
    var idClr = charIDToTypeID( "Clr " );
    var desc713 = new ActionDescriptor();
    var idRd = charIDToTypeID( "Rd  " );
    desc713.putDouble( idRd, 3.534862 );
    var idGrn = charIDToTypeID( "Grn " );
    desc713.putDouble( idGrn, 0.000000 );
    var idBl = charIDToTypeID( "Bl  " );
    desc713.putDouble( idBl, 0.000000 );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc712.putObject( idClr, idRGBC, desc713 );
    var idAntA = charIDToTypeID( "AntA" );
    desc712.putBoolean( idAntA, true );
    var idInvr = charIDToTypeID( "Invr" );
    desc712.putBoolean( idInvr, true );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc712.putUnitDouble( idOpct, idPrc, 50.000000 );
    var idlagl = charIDToTypeID( "lagl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc712.putUnitDouble( idlagl, idAng, 90.000000 );
    var idDstn = charIDToTypeID( "Dstn" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc712.putUnitDouble( idDstn, idPxl, 50.000000 );
    var idblur = charIDToTypeID( "blur" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc712.putUnitDouble( idblur, idPxl, 60.000000 );
    var idMpgS = charIDToTypeID( "MpgS" );
    var desc714 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc714.putString( idNm, """线性""" );
    var idShpC = charIDToTypeID( "ShpC" );
    desc712.putObject( idMpgS, idShpC, desc714 );
    var idChFX = charIDToTypeID( "ChFX" );
    desc632.putObject( idChFX, idChFX, desc712 );
    var idpatternFill = stringIDToTypeID( "patternFill" );
    var desc715 = new ActionDescriptor();
    var idenab = charIDToTypeID( "enab" );
    desc715.putBoolean( idenab, true );
    var idpresent = stringIDToTypeID( "present" );
    desc715.putBoolean( idpresent, true );
    var idshowInDialog = stringIDToTypeID( "showInDialog" );
    desc715.putBoolean( idshowInDialog, true );
    var idMd = charIDToTypeID( "Md  " );
    var idBlnM = charIDToTypeID( "BlnM" );
    var idDrkn = charIDToTypeID( "Drkn" );
    desc715.putEnumerated( idMd, idBlnM, idDrkn );
    var idOpct = charIDToTypeID( "Opct" );
    var idPrc = charIDToTypeID( "#Prc" );
    desc715.putUnitDouble( idOpct, idPrc, 42.000000 );
    var idPtrn = charIDToTypeID( "Ptrn" );
    var desc716 = new ActionDescriptor();
    var idNm = charIDToTypeID( "Nm  " );
    desc716.putString( idNm, """$$$/Patterns/Defaults/RightDiagonalLine1=Right Diagonal Line 1""" );
    var idIdnt = charIDToTypeID( "Idnt" );
    desc716.putString( idIdnt, """bf565312-67b6-1177-9181-9d5762aa7056""" );
    var idPtrn = charIDToTypeID( "Ptrn" );
    desc715.putObject( idPtrn, idPtrn, desc716 );
    var idScl = charIDToTypeID( "Scl " );
    var idPrc = charIDToTypeID( "#Prc" );
    desc715.putUnitDouble( idScl, idPrc, 100.000000 );
    var idAlgn = charIDToTypeID( "Algn" );
    desc715.putBoolean( idAlgn, true );
    var idphase = stringIDToTypeID( "phase" );
    var desc717 = new ActionDescriptor();
    var idHrzn = charIDToTypeID( "Hrzn" );
    desc717.putDouble( idHrzn, 0.000000 );
    var idVrtc = charIDToTypeID( "Vrtc" );
    desc717.putDouble( idVrtc, 0.000000 );
    var idPnt = charIDToTypeID( "Pnt " );
    desc715.putObject( idphase, idPnt, desc717 );
    var idpatternFill = stringIDToTypeID( "patternFill" );
    desc632.putObject( idpatternFill, idpatternFill, desc715 );
    var idLefx = charIDToTypeID( "Lefx" );
    desc631.putObject( idT, idLefx, desc632 );


    var ob = mu.actionDescriptorToObject(desc631);
    var ad = mu.objectToActionDescriptor(ob);
    executeAction( idsetd, ad, DialogModes.NO );




    // ActionDescriptor 转换到 JSON ---------------------------------
    // ActionDescriptor -> Object -> JSON
    log("3. ActionDescriptor 转换到 JSON");
    var desc443 = new ActionDescriptor();
    var idLvl = charIDToTypeID( "Lvl " );
    desc443.putInteger( idLvl, 0 );
    var idStte = charIDToTypeID( "Stte" );
    var idStte = charIDToTypeID( "Stte" );
    var idexit = stringIDToTypeID( "exit" );
    desc443.putEnumerated( idStte, idStte, idexit );
    var idTool = charIDToTypeID( "Tool" );
    var desc444 = new ActionDescriptor();
    var idIdnt = charIDToTypeID( "Idnt" );
    desc444.putString( idIdnt, """pntb""" );
    var idTtl = charIDToTypeID( "Ttl " );
    desc444.putString( idTtl, """画笔工具""" );
    var idTool = charIDToTypeID( "Tool" );
    desc443.putObject( idTool, idTool, desc444 );
    var idKnd = charIDToTypeID( "Knd " );
    var idKnd = charIDToTypeID( "Knd " );
    var idPnt = charIDToTypeID( "Pnt " );
    desc443.putEnumerated( idKnd, idKnd, idPnt );
    var idkcanDispatchWhileModal = stringIDToTypeID( "kcanDispatchWhileModal" );
    desc443.putBoolean( idkcanDispatchWhileModal, true );

    obo_ad(desc443);

}